### ISSUE TITLE
Cannot find module 'underscore'

### ISSUE THREAD

**Issue by ko0f** [Stockflare/lambda-dynamo-to-elasticsearch#1]
There's an error when running the script - `Cannot find module 'underscore'`

**Comment by stratmm** [comment]
Hi @ko0f,

How have you deployed the lambda function, have you used the `grunt lambda_package` to correctly package the function for deployment?

If you are trying to test it locally you will need to use the `grunt lambda_invoke` command to run it.

Have you run `npm install` locally?

Can you please attach some log output?

**Comment by ko0f** [comment]
@stratmm I've copied the script's text manually, assuming it's using standard Lambda libraries.

**Comment by stratmm** [comment]
If you check the `package.json` you will see all the dependencies.

```
{
  "name": "lambda-dynamo-to-elasticsearch",
  "description": "Provides a DynamoDB Stream to Elasticsearch pipeline",
  "version": "0.0.2",
  "private": "true",
  "dependencies": {
    "aws-sdk": "^2.1.40",
    "elasticsearch": "^8.2.0",
    "http-aws-es": "^1.1.1",
    "moment": "^2.10.6",
    "underscore": "^1.8.3",
    "when": "^3.7.4"
  },
  "devDependencies": {
    "grunt": "0.4.*",
    "grunt-pack": "0.1.*",
    "grunt-aws-lambda": "0.7.*",
    "npm": "^2.2.0"
  },
  "bundledDependencies": []
}
```
